server:
  port: 0

spring:
  application:
    name: user
  mvc:
    log-request-details: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
  datasource:
    password: Error34!
    username: root
    url: R2DBC:mariadb://localhost:3306/database?createDatabaseIfNotExist=true&serverTimezone=UTC&useUnicode=yes&characterEncoding=utf8
    driver-class-name: org.mariadb.jdbc.Driver
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/database
    username: root
    password: Error34!
    properties:
      lock_timeout: 40000
      statement_timeout: 40000
      idle_in_transaction_session_timeout: 40000
      connectTimeout: PT55S
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org:
      springframework:
        web: debug
        security:
          oauth2: info
    com:
      netflix:
        discovery: error

service:
  message: "Hello World!"
  secret: "2b44b0b00fd822d8ce753e54dac3dc4e06c2725f7db930f3b9924468b53194dbccdbe23d7baa5ef5fbc414ca4b2e64700bad60c5a7c45eaba56880985582fba4"
  expiration: "36000000"
