spring:
  application:
    name: gateway
  devtools:
    livereload:
      port: 35730

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org:
      springframework:
        web: debug
    com:
      netflix:
        discovery: error