server:
  port: 8761

spring:
  application:
    name: eureka
  devtools:
    livereload:
      port: 35729
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10



logging:
  level:
    org:
      springframework:
        web: debug
        security:
          oauth2: info
    com:
      netflix:
        discovery: error