server:
  port: 55500

spring:
  application:
    name: auth
  mvc:
    log-request-details: true
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/database?serverTimezone=UTC&useUnicode=yes&characterEncoding=utf8
    username: root
    password: Almafa123

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

logging:
  level:
    org:
      springframework:
        web: debug
    com:
      netflix:
        discovery: error